# Generated by Django 2.1.2 on 2018-10-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rezept',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='rezept',
            old_name='Description',
            new_name='description',
        ),
    ]
