# Generated by Django 2.1.2 on 2018-10-30 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0002_auto_20181030_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200, verbose_name='Category')),
            ],
        ),
        migrations.RenameField(
            model_name='rezept',
            old_name='description',
            new_name='zubereitung',
        ),
        migrations.AddField(
            model_name='rezept',
            name='zutaten',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rezept',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hugo.Category'),
        ),
    ]
