# Generated by Django 2.1.2 on 2018-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0003_auto_20181030_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Category'),
        ),
    ]
