# Generated by Django 2.1.2 on 2018-10-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0004_auto_20181030_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zutaten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zutat', models.CharField(max_length=200, null=True, verbose_name='Zutat')),
            ],
        ),
        migrations.AlterField(
            model_name='rezept',
            name='zutaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hugo.Zutaten'),
        ),
    ]
