# Generated by Django 2.1.2 on 2018-10-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0005_auto_20181030_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezept',
            name='zutaten',
        ),
        migrations.AddField(
            model_name='zutaten',
            name='rezept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hugo.Rezept'),
        ),
    ]
