# Generated by Django 2.1.2 on 2018-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0006_auto_20181030_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zutaten',
            old_name='rezept',
            new_name='rezept_id',
        ),
        migrations.AlterField(
            model_name='rezept',
            name='img_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
