# Generated by Django 2.1.2 on 2018-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0007_auto_20181030_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
