# Generated by Django 2.1.2 on 2018-10-30 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0008_rezept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zubereitung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zubereitung', models.CharField(max_length=2000, null=True, verbose_name='zubereitung')),
            ],
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='zubereitung',
        ),
        migrations.AlterField(
            model_name='rezept',
            name='img_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='zutaten',
            name='zutat',
            field=models.CharField(max_length=2000, null=True, verbose_name='Zutat'),
        ),
        migrations.AddField(
            model_name='zubereitung',
            name='rezept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hugo.Rezept'),
        ),
    ]
