# Generated by Django 2.1.2 on 2019-01-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo', '0010_auto_20181030_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adressen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=2000, null=True, verbose_name='name1')),
                ('name2', models.CharField(max_length=2000, null=True, verbose_name='name2')),
                ('nachname', models.CharField(max_length=2000, null=True, verbose_name='nachname')),
                ('strasse', models.CharField(max_length=2000, null=True, verbose_name='strasse')),
                ('plz', models.CharField(max_length=2000, null=True, verbose_name='plz')),
                ('ort', models.CharField(max_length=2000, null=True, verbose_name='ort')),
            ],
        ),
        migrations.CreateModel(
            name='Geburtstage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=2000, null=True, verbose_name='vorname')),
                ('nachname', models.CharField(max_length=2000, null=True, verbose_name='nachname')),
                ('datum', models.DateField(null=True, verbose_name='datum')),
            ],
        ),
    ]
